# Generated by Django 6.0.5 on 2026-09-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13, UPC-A, QR or any barcode value', max_length=100, null=True, unique=True),
        ),
    ]
